//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class IconMap
    {
        public int Id { get; set; }
        public int IconCategoryId { get; set; }
        public string SourceValue { get; set; }
        public string Icon { get; set; }
        public bool Active { get; set; }
    }
}
