//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapItem
    {
        public int Id { get; set; }
        public int MapId { get; set; }
        public string SourceField { get; set; }
        public string DestinationRoot { get; set; }
        public string DestinationPath { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> IndexedProperty { get; set; }
    
        public virtual Map Map { get; set; }
    }
}
