//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTag
    {
        public int Id { get; set; }
        public string Tag { get; set; }
        public string ModelPath { get; set; }
        public bool Active { get; set; }
    }
}
