//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgentX_V7Entities : DbContext
    {
        public AgentX_V7Entities()
            : base("name=AgentX_V7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataProvider> DataProviders { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<MapItem> MapItems { get; set; }
        public virtual DbSet<PageRegistryDataProvider> PageRegistryDataProviders { get; set; }
        public virtual DbSet<PageRegistryItem> PageRegistryItems { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<ProfilePageRegistryItem> ProfilePageRegistryItems { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<AgentMessage> AgentMessages { get; set; }
        public virtual DbSet<AgentProfile> AgentProfiles { get; set; }
        public virtual DbSet<AgentProfileThreshold> AgentProfileThresholds { get; set; }
        public virtual DbSet<EffortEfficiency> EffortEfficiencies { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<RiskClassification> RiskClassifications { get; set; }
        public virtual DbSet<Target> Targets { get; set; }
        public virtual DbSet<TargetSetting> TargetSettings { get; set; }
        public virtual DbSet<CustomerIcon> CustomerIcons { get; set; }
        public virtual DbSet<ExpressionType> ExpressionTypes { get; set; }
        public virtual DbSet<IconCategory> IconCategories { get; set; }
        public virtual DbSet<IconExpression> IconExpressions { get; set; }
        public virtual DbSet<IconMap> IconMaps { get; set; }
        public virtual DbSet<MessageTag> MessageTags { get; set; }
        public virtual DbSet<MessageTemplate> MessageTemplates { get; set; }
        public virtual DbSet<MessageTemplateTag> MessageTemplateTags { get; set; }
        public virtual DbSet<MessageTemplateType> MessageTemplateTypes { get; set; }
        public virtual DbSet<MessageThreshold> MessageThresholds { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<MessageEfficiencyThreshold> MessageEfficiencyThresholds { get; set; }
    }
}
