//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageRegistryDataProvider
    {
        public int Id { get; set; }
        public int PageRegistryItemId { get; set; }
        public int DataProviderId { get; set; }
        public int ExecutionOrder { get; set; }
        public Nullable<bool> StopOnError { get; set; }
        public bool Active { get; set; }
    
        public virtual DataProvider DataProvider { get; set; }
        public virtual PageRegistryItem PageRegistryItem { get; set; }
    }
}
